import { NextResponse } from 'next/server';
import { Agent } from '@/lib/agent/core';
import { AgentRequestSchema } from '@/lib/validators';

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const validation = AgentRequestSchema.safeParse(body);

        if (!validation.success) {
            return NextResponse.json({ error: validation.error.errors[0].message }, { status: 400 });
        }

        const { prompt } = validation.data;

        console.log(`[API] Starting agent with prompt: ${prompt}`);

        // Initialize Agent with the user's prompt
        const agent = new Agent(prompt);

        // Run the agent loop
        await agent.run();

        // In a real implementation, we would return the result/artifacts.
        // For now, valid simulation logs are in the console and files in `output/`

        return NextResponse.json({
            status: 'success',
            message: 'Agent finished mission.',
            // Mocking return data for UI
            artifacts: [
                { path: 'index.tsx', content: '// Generated by Olynero AI' }
            ]
        });

    } catch (error: any) {
        console.error('[API] Agent error:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
