"use server";

import { db } from "@/lib/db";
import { revalidatePath } from "next/cache";

export async function generateDockerfileAction(projectId: string) {
    const content = `# Generated by Olynero
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

# Default command, adjust as needed (e.g. 'npm run preview' for Vite, 'npm start' for Next.js)
CMD ["npm", "run", "start"]
`;

    try {
        // Check if exists
        const existing = await db.file.findUnique({
            where: {
                projectId_path: {
                    projectId,
                    path: "Dockerfile",
                },
            },
        });

        if (existing) {
            return { success: false, message: "Dockerfile already exists" };
        }

        await db.file.create({
            data: {
                projectId,
                path: "Dockerfile",
                content,
            },
        });

        revalidatePath(`/project/${projectId}`);
        return { success: true };
    } catch (error) {
        console.error("Failed to generate Dockerfile:", error);
        return { success: false, message: "Failed to generate Dockerfile" };
    }
}
