"use server";

import { auth } from "@/auth";
import { db } from "@/lib/db";
import { revalidatePath } from "next/cache";

export async function generateDockerfileAction(projectId: string) {
    const session = await auth();
    if (!session?.user?.id) {
        return { success: false, message: "Unauthorized" };
    }

    // Verify project ownership
    const project = await db.project.findUnique({
        where: { id: projectId },
        select: { userId: true },
    });
    if (!project || project.userId !== session.user.id) {
        return { success: false, message: "Unauthorized: you do not own this project" };
    }

    const content = `# Generated by Olynero
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

# Default command, adjust as needed (e.g. 'npm run preview' for Vite, 'npm start' for Next.js)
CMD ["npm", "run", "start"]
`;

    try {
        const existing = await db.file.findUnique({
            where: {
                projectId_path: {
                    projectId,
                    path: "Dockerfile",
                },
            },
        });

        if (existing) {
            return { success: false, message: "Dockerfile already exists" };
        }

        await db.file.create({
            data: {
                projectId,
                path: "Dockerfile",
                content,
            },
        });

        revalidatePath(`/project/${projectId}`);
        return { success: true };
    } catch (error) {
        console.error("Failed to generate Dockerfile:", error);
        return { success: false, message: "Failed to generate Dockerfile" };
    }
}
